# Set compiler
CC = g++

#Compile flags (-c to output object file .o)
CFLAGS = -Wall -Wextra -Wpedantic -std=c++11

all: q1 q2 q3 q4

q1: 
	$(CC) $(CFLAGS) q1.cpp q1_main.cpp -o q1.exe

q2: 
	$(CC) $(CFLAGS) q2.cpp q2_main.cpp -o q2.exe

q3: 
	$(CC) $(CFLAGS) q3.cpp q3_main.cpp -o q3.exe

q4: 
	$(CC) $(CFLAGS) q4.cpp q4_main.cpp -o q4.exe

clean:
	rm *.exe